### ISSUE TITLE
EC2 NAT Gateway

### ISSUE THREAD

**Issue by isaac-s** [cloudify-incubator/cloudify-boto3-plugin#13]
- [x] AWS::EC2::NatGateway

**Comment by joshuap-cfy** [comment]
I think this issue can be re-opened:

NonRecoverableError in NATGateway Configure task causing the install workflow to abort.

NATGateway instance “nat-0fdfd7906b1621baf” but it doesn’t exist in my AWS vpc (already deleted by uninstalling of a previous deployment) and I don’t know why it can interfere with the install workflow of a new deployment.

<network> 'install' workflow execution failed: RuntimeError: Workflow failed: Task failed 'cloudify_boto3.ec2.resources.nat_gateway.create' -> EC2 NAT Gateway ID# "nat-0fdfd7906b1621baf" no longer exists but "fail_on_missing" set

**Comment by EarthmanT** [comment]
Published Fix in m6
