### ISSUE TITLE
possible wrong usage of utils.get_resource_id/utils.get_resource_string with realation_ship context

### ISSUE THREAD

**Issue by 0lvin** [cloudify-incubator/cloudify-boto3-plugin#23]
We have use wrong usage of utils.get_resource_id(fixed in #28)  without node/instance parameter in:
* https://github.com/cloudify-incubator/cloudify-boto3-plugin/blob/dev/cloudify_boto3/common/utils.py#L37
* https://github.com/cloudify-incubator/cloudify-boto3-plugin/blob/dev/cloudify_boto3/rds/resources/option.py#L43
* https://github.com/cloudify-incubator/cloudify-boto3-plugin/blob/dev/cloudify_boto3/rds/resources/instance_read_replica.py#L146

Also in https://github.com/cloudify-incubator/cloudify-boto3-plugin/blob/dev/cloudify_boto3/rds/resources/option.py#L73 we have unsymmetric usage of remove_option/include_option

In attach possible use of resource_id from source but in detach_from only possible input is resource_config

**Comment by EarthmanT** [comment]
Fixed in #28.
