### ISSUE TITLE
IAM

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-boto3-plugin#3]
- [x] AWS::IAM::AccessKey
- [x] AWS::IAM::User
- [x] AWS::IAM::Role
- [x] AWS::IAM::Policy
- [x] AWS::IAM::InstanceProfile
- [x] Unit tests

**Comment by 01000101** [comment]
Role and Policy are now committed and showcased in the `examples/lambda-features-demo/blueprint.yaml` blueprint.

**Comment by 01000101** [comment]
All required IAM features have been committed. Please review.

**Comment by isaac-s** [comment]
@EarthmanT where is `InstanceProfile` implemented? not found in `plugin.yaml`.
