### ISSUE TITLE
Route 53

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-boto3-plugin#4]
- [x] Create/Delete Zone
- [x] Create Record Set
- [x] Change Record Set
- [ ] Check Availability
- [ ] Register
- [ ] Unit tests

**Comment by 01000101** [comment]
@EarthmanT  What does "Check Availability" mean? Do you mean implementing DNS Health Checks?

**Comment by 01000101** [comment]
@EarthmanT For the "Register" type (registering a domain name), this can take a really long time to fulfill (hours, days, etc...) and often has a manual step where Route53 may send a confirmation email or something that must be clicked on before it finalizes. Should the operation for "create" really throw a RecoverableError and spin until completed or just acknowledge the pending state and continue?
