### ISSUE TITLE
force delete bucket

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-incubator/cloudify-boto3-plugin#53]

**Comment by isaac-s** [comment]
@EarthmanT how was it implemented? Looking at the code, I see that we delete all the contents of the bucket before removing it. Which means that "force delete" isn't really an option — it's implied. Can you confirm?

Also, which milestone is it available in?

**Comment by EarthmanT** [comment]
Exactly. It deletes objects in the bucket and then deletes the bucket.
1.0.0m4.
