### ISSUE TITLE
Provide example for attaching an ELB to an AutoScaling group

### ISSUE THREAD

**Issue by isaac-s** [cloudify-incubator/cloudify-boto3-plugin#63]

**Comment by EarthmanT** [comment]
There was a bug in < m4 that made one kind of subnet cause issues. example include. bug fixed in m5

**Comment by isaac-s** [comment]
@EarthmanT where is the example?

**Comment by EarthmanT** [comment]
https://github.com/cloudify-incubator/cloudify-boto3-plugin/blob/dev/examples/blueprint.yaml#L65
