### ISSUE TITLE
Route53 get_attribute: Suggest alternative to using get_attribute within node properties

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-incubator/cloudify-boto3-plugin#69]
There is a question around the resource_id "Endpoint.Address" supported by Cloudformation API, but possibly not the boto3 API, since we can't find a reference in boto3 to it:
http://boto3.readthedocs.io/en/latest/reference/services/route53.html

The example here is too general and doesn't use real values:
https://github.com/cloudify-incubator/cloudify-boto3-plugin/blob/1.0.0m5/examples/route53-feature-demo/blueprint.yaml#L38

instance created successfully, but the Route53 recordset with “Value” as “{ get_attribute: [ NODEDB, Endpoint.Address ] }” is created a “None” value

**Comment by EarthmanT** [comment]
The issue will be solved with https://github.com/cloudify-incubator/cloudify-boto3-plugin/issues/71.
