### ISSUE TITLE
EFS creation failed because of missing "CreationToken"

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-incubator/cloudify-boto3-plugin#72]
Creating EFS nodes with m5 results in an error shown below

017-06-08T18:54:09 CFY <network> [EFS_u5u3s9.configure] Task failed 'cloudify_boto3.efs.resources.file_system.create' -> Parameter validation failed:
Missing required parameter in input: "CreationToken"

File "/opt/mgmtworker/env/plugins/cloudify-boto3-plugin-1.0.0/lib/python2.7/site-packages/botocore/validate.py", line 291, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())
ParamValidationError: Parameter validation failed:
Missing required parameter in input: "CreationToken"

**Comment by EarthmanT** [comment]
Please provide documentation of the node template that failed. A Creation Token is a required parameter. It must be unique. Currently if the CreationToken is not provided, we generate one from a UUID.

**Comment by joshuap-cfy** [comment]
Ok, we can look in a log which will list which node template failed, is there a recommended log which will list this or should we look.

I'm currently look at this node:
 EFS:
    type: cloudify.nodes.aws.efs.FileSystem

I don't a token provided as a parameter, so the UUID method looks like the one being used.

**Comment by EarthmanT** [comment]
I have not been able to reproduce. Is the error consistent?
