### ISSUE TITLE
Do not allow conflicting resource_id/policy/resource names.

### ISSUE THREAD

**Issue by isaac-s** [cloudify-incubator/cloudify-boto3-plugin#78]

**Comment by isaac-s** [comment]
Examples / log files sent via email (confidentiality)

**Comment by EarthmanT** [comment]
Check that resource_id and PolicyName properties do not get confused between create and delete.

**Comment by EarthmanT** [comment]
updated the get_resource_id utility to work with a "resource_name" that is constant across all resources. Now there is a resolution process to get the resource_id: iface.resource_id > resource_config > resource_id from runtime_properties > resource_config from runtime properties > resource_config from node properties > resource_id from node_properties > ctx instance id.
