### ISSUE TITLE
Proxy Plugin Blueprint Upload Error

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-incubator/cloudify-boto3-plugin#80]
Used deployment proxy to implement the following use case:
· Given an existing deployment (deployment_id: network), which exposes several resources through outputs.
· Deploy and install another blueprint, which needs access to the resources created in the deployment above.
Tried to upgrade my proxy node to use the new version of the proxy plugin (1.2.2) following the example in this link: https://github.com/cloudify-incubator/cloudify-utilities-plugin/blob/1.2.2/cloudify_deployment_proxy/examples/test/deployment-proxy.yaml.

My question is: since I’m just importing outputs exposed by an existing deployment, why is it required to provide the “blueprint” input to the proxy node? If I set the blueprint input to empty values, I’m getting an error. The error appears to be resulted from the plugin trying to upload a blueprint. What’s the right way to use DeploymentProxy in this new version of 1.2.2?
Below is the previous template of the proxy node:
network_deployment_proxy:
type: cloudify.nodes.DeploymentProxy
properties:
inherit_outputs:
'privateSubnet0_id'
'privateSubnet1_id'
'publicSubnet0_id'
'publicSubnet1_id'
'commonSecurityGroup_id'
'elbAccessLoggingBucketAndPath'
interfaces:
cloudify.interfaces.lifecycle:
create:
inputs:
deployment_id: { get_input: network_deployment_id }
start:
inputs:
deployment_id:
{ get_input: network_deployment_id }
stop:
inputs:
deployment_id:
{ get_input: network_deployment_id }
Here is the new proxy node using https://raw.githubusercontent.com/cloudify-incubator/cloudify-utilities-plugin/1.2.2/plugin.yaml
network_deployment_proxy:
type: cloudify.nodes.DeploymentProxy
properties:
resource_config:
blueprint:
id: ''
blueprint_archive: ''
main_file_name: ''
deployment:
id:
{ get_input: network_deployment_id }
outputs:
key: network_proxy_output
Error:
2017-06-13T23:31:14 CFY <adm613a> [network_deployment_proxy_jsj244.create] Task failed 'cloudify_deployment_proxy.tasks.upload_blueprint' -> [Errno 2] No such file or directory: u''
Traceback (most recent call last):

**Comment by EarthmanT** [comment]
wrong project.
