### ISSUE TITLE
Can't delete a security group depended upon by a Autoscaling LaunchConfiguration

### ISSUE THREAD

**Issue by joshuap-cfy** [cloudify-incubator/cloudify-boto3-plugin#84]
Summary:
M7: (Priority 2) Can't delete a security group depended upon by a Autoscaling LaunchConfiguration
 
Symptom:
The uninstall workflow tries to delete a security group specified as a dependent in AG launch configuration. This task is not successful despite numerous retries. I try to manually delete the security group and got the following warning. The dependency relationships of autoscaling group -> LaunchConfiguration -> Security Group, is contradict the deleting order enforced by AWS. AWS expects the ec2 instance of the autoscaling group be deleted first before the security group can be deleted.

Steps to reproduce:
1.         Deploy a blueprint with the nodes of one AutoscalingGroup, one LaunchConfiguration, and one SecurityGroup.
2.         Uninstall it. The first node to be deleted is the security group and the workflow is stuck as retries.

**Comment by EarthmanT** [comment]
This was resolved.
